version: "3.4"

services:
  unit-tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: word_clout:test-venv
    working_dir: /home
    volumes:
      - .:/home/
    container_name: src-unit-tests
    entrypoint: python3 -m pytest -c testing_framework/pytest.ini
