version: "3.4"

x-tests: &tests
  build:
    context: .
    dockerfile: Dockerfile
  image: word_clout:test-venv
  working_dir: /home
  volumes:
    - .:/home/

services:
  unit-tests:
    <<: *tests
    container_name: word_clout-unit-tests
    entrypoint: python3 -m pytest -c testing_framework/pytest.ini
